### ISSUE TITLE
Add a `debouncer`

### ISSUE THREAD

**Issue by bitsandfoxes** [getsentry/sentry-godot#22]
It’s easy for the SDK to end up capturing a ton of errors in a short amount of time. For example, if there's a script error in `_process`, the SDK can capture every single one. This could quickly burn through a user’s quota without providing much helpful info.

### Why this is a problem
- You can blow through your quota super fast i.e. with errors in `_process` or `_physics_process`
- Sending a bunch of errors in one go could impact performance, especially during gameplay.
- A bunch of duplicate errors are not going to be terribly useful anyway

### How this could help
Adding a debounce feature would make error reporting smarter by:

- Limiting frequency: Only capturing one error every X seconds, for example. We have a very naive implementation like this in the Unity SDK
- Skipping duplicates: If the same error happens repeatedly (like in a loop), don’t capture it every time. But how would we detect duplicates?

**Comment by limbonaut** [comment]
> how would we detect duplicates?

Maybe keeping a count hashed by `(file, lineno)`

**Comment by limbonaut** [comment]
Working on a multi-layered solution, described in #28
