### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by limbonaut** [getsentry/sentry-godot#43]
For release process, we need version tracking. Ideally, we want to see where the build comes from (which commit) and differentiate release builds from others (custom builds, PR/CI builds, etc.). 

Godot currently doesn't track versions for extensions, but that might change. GDScript-based plugins usually have a version string following semantic versioning (not enforced). 

The SDK version should be reported in captured events.

**Comment by bruno-garcia** [comment]
In Unity and .NET we append the commit sha after the version:

![Image](https://github.com/user-attachments/assets/654a0954-e960-4ffe-a24d-5b873efdc379)
